update moose etl scripts to allow domain to passed all the way down the chain

diff --git a/moose-etl/cpm-pr/master-script b/moose-etl/cpm-pr/master-script
--- a/moose-etl/cpm-pr/master-script
+++ b/moose-etl/cpm-pr/master-script
@@ -14,11 +14,23 @@ collection="land-cpm"
 unscaled_variable_resolution="2.2km"
 data_variable="pr"
 variable_config_name="cpm-${data_variable}"
-domain="london"
 frequency="day"
 src_vars=(lsrain lssnow)
-target_sfs=(1 2 4 8)
+target_sfs=(1 4)
 variable_sfs=(1 8 gcm)
+
+while getopts ":d:" opt; do
+  case ${opt} in
+    d )
+      domain=${OPTARG}
+      ;;
+   \? )
+     echo "Invalid Option: -${OPTARG}" 1>&2
+     exit 1
+     ;;
+  esac
+done
+shift $((OPTIND -1))
 
 set -x
 
